##
# This file is part of the pl.wrzasq.cform.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2025 © by Rafał Wrzeszcz - Wrzasq.pl.
##

version: 2
updates:
    -
        package-ecosystem: "maven"
        directory: "/"
        schedule:
            interval: "daily"
        groups:
            aws-sdk:
                patterns:
                    - "software.amazon.awssdk:*"
            jackson:
                patterns:
                    - "com.fasterxml.jackson.core:*"
                    - "com.fasterxml.jackson.datatype*"
                    - "com.fasterxml.jackson.module*"
    -
        package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily"
