##
# This file is part of the pl.wrzasq.cform.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2020 © by Rafal Wrzeszcz - Wrzasq.pl.
##

#FIXME: https://github.com/travis-ci/travis-ci/issues/753

language: "java"

sudo: false

dist: "trusty"

branches:
    except:
        - "/^release-/"

jdk:
    - "openjdk11"
    - "oraclejdk11"

env:
    global:
        -
            secure: |-
                iNJG0bNxxlwbKYY4qUWbwEwIJ5AI+g0e5Y3bFtSomlO5T+0mulgftcVas8h4Qi6iuN+341hhGFJuxY9OBDSr6cw0u6yodmHhDA6BTKA
                PsKT2va9duOF9lg/jUBao9omfhy0tLKKmSzSAUk2jYsANfD4IB+yEqBtuwW3VQrPlnZh1O1AydtkSV9Bgl5TQ3qf6Szq/bc+AxKOAzN
                0g/2yzRCdxM0vU0AhASJ/aUuZn07sceHxNZRdqSEibFM4TJMic2xkVvOVUw2NMpsZdQDIqhW9FHeVWN95x15Cg4YuMb2qFNjiP49T0Z
                v2Vk0EdNcsjNqBaoaBDeKuESnJCD5EYhDHqUEVRaNm0KjopDxqVBnp2NXWDMu7+KHkO2A3I5ztG5IIJgRvzv5V2Aak3T7yO0E2buQF5
                xG1re4kaGYXfB4cCFltmbNXwaUbHNdjAl7cp9BfL5TawuRjTgQDDlRDwVJtfjMsW21Xf2T52dlxsa4+8jMQkmDgZm8Mlt5PLeEMcegO
                qX54W9QlwLB029f9/1GqltChoV3vThfrMFyjECZBt2UZt8Wl1SgmQDIZ9wBbpYoSyOZ+vkPuZgLLgmgzsgGz+3B91ugIPTScTswisoW
                zeIdX1YKeo/0X9l1sJca59cKHeNo2LUjvTGqUtZH0aPeHShjtL/i6L2uVKVkCi/v0=
        -
            secure: |-
                RsYM/BxaBwuwEAzGmTk6QPnNY6mQRyPtutDfXEm+PUR3dEWKb5/tzbIQNIFGZO+H8K8Pmymxs9NW9fHJ5zuLe65x1+XfRYkdWDWWcUq
                aum4cLe8rKNBtGByABOtXk7oM7MggRNPVIWDWd0bqA1PC1/8V2Kn4+UIhkmbnUMPc3lyMmiXOYuq/Kp9g8hSdATEleyF4B5bcYKIyLT
                TlSmV774ssHnNOcS4FP4Mx3KHnmB3uCxBsIIr4/HvQBsa30S1QhevurTZ4IC8/AK58uZN1w/9e2Buc5wZy7tDxjdJaaZieohr3ozg+P
                ZgG0cXYpb8JBSg1K6GglOf6r2MulIR5TWbCbcPK1YN9UgyBwLoy+1D0G3pop4NUI5PwvuOWTIQhn65NdvgtB4x74cqlWLGqxtox7Taz
                De9Iu4fFSC1fxIz4gP2b0Re34TcVRZwEhJAwDslyTtdz+L8KY3osfEZExGqT0ogueJnt6kFtj4tkLczRT26c6VFTbwzkxvwnvpXLMle
                RG4bYyJxRG4zbqv77sp/nLhdS7mjVjFErjvjp+zPLiMQQk/JtZBwhfKiICOLeVOQNfWL/a2F9p1mTpWtP/QwwHD+2iTOq7ILzSb+gkr
                fVBS49rTdvD53pefNzGXHIESZ1V5wMm9xFDymJKnBNLSn73Vh3vXoreTiHNtlTlR4=
        -
            secure: |-
                jT7r04xwphXl5IL4LScnx0O+tRYptoX/Tft6SnuaSfv5Bb8UTej+bGJGIKonZlhdt7i+RBAxE6lo43rJU1DIZL3E1qe5yDLkj6BI7X+
                U5fQpB2MboEjheZG9Z4Y7BsZt98+rfqQgMp02QGrTfSDubSUXFJbQXEJL5nyoYfRKPDOnxe9y/JYecfg64tlSzeEpClJrhdUMGKkIS5
                Gd7HoMbjskAoH0BkOV+vC4O1MpquTjblPw42Xfjfgz6eVlpqUDzp9bJknTVoOX02nYTZR6+H1hEcFaztVKsZr3po0Y8s41eeIh+fglT
                EE1Z5xO05zERo4jgdghp8M8WAdGOwV+g3t66g81rqjjQ/n9R5JLYLkaVexZFYdfQImpblwT2+YEPkZ6Hn3bwAgKEGMYCFZBovBOs915
                /irudwbwwvd7ez9A0ZRrZnK8CdiJxIwRSv4QeAb5+Q1iP6bayYluzl/AxGLUEwtVZQ5cDZia/UPl7edo5g5xrKukDKEgTGvJNdHBzZU
                PVGKF+a0v6161aoAs+uKw73I1CpLdFRNHvTMRD9OlG8EwzHcnAuU21yE5C2LAfkbbLDW8x2WpNyL3TiO0cZnJoQHbxtXq+Arbk2Wpej
                t3P7S47OvUL55+YM+I+Ot9/AEQsti1py37t4tmJzJmQelBs23wlDUBXR3F/O48PGs=
        -
            secure: |-
                A9Xjgz0A2bWbSkvbWyTR7bqjroR9GYGpHEjqcf/LqgW8kuPo890mrUkQOyM4wWm775f9LHE3ZJ6EnSiwrrFHEViOWKUvyoqMdM39VPW
                KgT0Zu4Xmy6wb2wOnFhfU2mtSPxS4MtexeL3sMw+ZevdHY94ZUW3REbMp0r5UhOPORWwabJCUjPqV2zDg3OyT7TvXyftT/8rtrvPnML
                MgYOgWGh6yH8DrGxsPLXRFSpuoFpz/snbXcNDRUmX0U3wcyns4gsrovfhrtkrp+6l2ImO/5YdIs1F4j2qaG7QFdXUw8NseEnvuW9kRu
                hkUGAMXpR08N3uqSsVIum1tWYJT/sHOy++DhxowhvpJm/h71iM0hqt9NfBH+AV3YZzEn6CHIbPZs1J09/F6/rDmPlRZoRzdQOAXku8+
                Vy+tUgReLQrNftpTg91/b3KjQzVch+f6lFVwThFfwWXo9Y8aLfllgn/JhDmM0SWgIXtgkgP/lODZh8O6sDJ5aCl1+28I4Y9tj9+KCQu
                a4Ag+xVHKr69Ba9+dZ+VtceyY2jEUsde6AO9IOzxcXm/++r0Mg2d2UkJ+rk8jTPVc3dWiWIGdjdihP6zbFM5xUL6U13ez8eSSfJ/XWd
                sXOtZpjQHUPm0/2RkNYRaoQpUxr2wCxEjKSNsZFmkjDfuxZp4x0UI9zxqAbhyxKM4=
        -
            secure: |-
                p8IxVk6eNQlIkcs9zcMoV05pzlIfyMjuBobo64ZwXDCLRMx+3mT0p+lfgw/D+Wsj8nOpnc+E+GDB91eQe4KtcVePo16kFMf1KdD42EZ
                MamDdZlwAMaayVrRfkE2pRmSy5c7zqDY2RIBLdBuNLaU+FuNiqc0iDZpFaYnJ0y2gRzzgT4l2M8OqUZdmnIRv91UmnzAHdEtocliAq3
                3gekuB+8+Qu7eie/AEgGi4I8ZTUgyF7IhlILBzGfz1vzOS87fzurQSdj0pJR166C826wnla8yJ4RsKKdhCwP+LHPV2jOsEzU/6weMRV
                VcHhTqcoPHfhZoqMBjhDxTiCUMgJzoe1T6Ps9WGrgt9hXyUV4gbxMR+qxrFJR9rroWoYLCIZaEPbBdob0gv+Jd6K+r8XBwRW1/+uzZX
                IxtBcTw5nmi1ldy43trmGeQ/5PK6b587k1Q4gv633Wc2+jSBsIhS7CIDrVbLn21QHtThdFbwTqElrYcxbUHgJS6lIHIcrg8KWkMMThm
                giJGtTktWvhUbGbT1yP1KDvDQzARiSfBBlnP/vE7GE5EKWq/8IlDpOl26ol1hmGK0m+2tHd/tnT2g866iFvu1ZYEsx0Tz1nbm3feiO7
                jXliEWilTReI2SH48LIYHRBUMuS8ib0GUFnLTM95OdTpPSSAZ1hcH+5PZpkStIB5k=

# this is not a boolean, this is a Linux `true` command to simply override this step
install: "true"

script: "mvn -B -e verify site"

after_script: "mvn -B -e coveralls:report"

before_deploy:
    - "eval \"$(ssh-agent -s)\""
    - "git config user.name \"Travis CI\""
    - "git config user.email \"office@wrzasq.pl\""
    - "openssl aes-256-cbc -md sha256 -k \"${SECRET}\" -in .travis/gpg_key.enc -out .travis/gpg_key -d"
    - "openssl aes-256-cbc -md sha256 -k \"${SECRET}\" -in .travis/id_rsa.enc -out .travis/id_rsa -d"
    # this is needed to avoid duplicated key error as we have two deploys on `master`
    - "rm -f ~/.gnupg/*.gpg"
    - "gpg --fast-import .travis/gpg_key"
    - "chmod 600 .travis/id_rsa"
    - "ssh-add .travis/id_rsa"
    - "echo -e \"Host github.com\\n    StrictHostKeyChecking no\\n\" >> ~/.ssh/config"
    # this actually does the job, but we need it to produce artifacts for "releases" provider
    # entire "before_deploy" will not be executed if there is no deploy to be processed
    - "./.travis/release.sh"
    - "export TRAVIS_TAG=$(git describe --abbrev=0)"

deploy:
    -
        provider: "releases"
        skip_cleanup: true
        api_key: "${GITHUB_TOKEN}"
        file_glob: true
        file: "*/target/*.jar"
        on:
            branch: "master"
            condition: "${TRAVIS_EVENT_TYPE} == push"
            jdk: "oraclejdk11"

cache:
    directories:
        - "${HOME}/.m2/"

before_cache: "rm -rf ${HOME}/.m2/repository/pl/wrzasq/cform"

notifications:
    webhooks:
        urls:
            - "https://webhooks.gitter.im/e/1bbc1730df2e380aee78"
