#!/bin/bash
##
# This file is part of the pl.wrzasq.cform.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2021 © by Rafał Wrzeszcz - Wrzasq.pl.
##

set -euo pipefail

./cform-resource-aws-account.bin
