##
# This file is part of the pl.wrzasq.cform.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2020 © by Rafał Wrzeszcz - Wrzasq.pl.
##

on:
    push:
        tags-ignore: "**"
        branches: "**"
    pull_request:
        branches: "**"
    schedule:
        -
            cron: "0 3 * * 0"

jobs:
    build:
        if: "!contains(github.event.head_commit.message, '[skip ci]') || (github.event_name == 'schedule')"
        runs-on: "ubuntu-18.04"
        strategy:
            matrix:
                java:
                    - "11"
                    - "12"
                    - "13"
                    - "14"
                    # (de)lombok doesn't support Java 15
                    #- "15"
        steps:
            -
                uses: "actions/checkout@v2.3.3"
            -
                uses: "actions/setup-java@v1.4.3"
                with:
                    java-version: "${{ matrix.java }}"
            -
                uses: "actions/cache@v2.1.2"
                with:
                    path: "~/.m2/"
                    key: "${{ runner.os }}-m2-${{ matrix.java }}"
            -
                run: "mvn -B -e verify site"

    release:
        if: "(github.event_name == 'push') && (github.event.ref == 'refs/heads/master')"
        runs-on: "ubuntu-18.04"
        needs: "build"
        steps:
            # workspace preparation
            -
                uses: "actions/checkout@v2.3.3"
            -
                uses: "actions/setup-java@v1.4.3"
                with:
                    java-version: "11"
            -
                uses: "actions/cache@v2.1.2"
                with:
                    path: "~/.m2/"
                    key: "${{ runner.os }}-m2-11"
            # Git setup
            -
                run: "git config user.name \"GitHub Actions\""
            -
                run: "git config user.email \"office@wrzasq.pl\""
            -
                uses: "crazy-max/ghaction-import-gpg@v3.0.1"
                with:
                    gpg-private-key: "${{ secrets.GPG_PRIVATE_KEY }}"
            # first make current version release
            -
                run: "mvn -B versions:set versions:commit -DremoveSnapshot=true"
            -
                run: "git add -u"
            -
                run: "git commit -m \"[skip ci] Automated release release.\""
            # perform a release
            -
                run: "mvn -B -e clean deploy -P deploy --settings .github/settings.xml"
                env:
                    GITHUB_ACTOR: "${{ secrets.GITHUB_ACTOR }}"
                    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                    OSSRH_USERNAME: "${{ secrets.OSSRH_USERNAME }}"
                    OSSRH_PASSWORD: "${{ secrets.OSSRH_PASSWORD }}"
                    GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"
            # now create a new version commit
            -
                run: "mvn -B build-helper:parse-version versions:set versions:commit -DnewVersion=\"\\${semver.majorVersion}.\\${semver.minorVersion}.\\${semver.nextIncrementalVersion}-SNAPSHOT\""
            -
                run: "git add -u"
            -
                run: "git commit -m \"[skip ci] New version bump.\""
            -
                uses: "ad-m/github-push-action@v0.6.0"
                with:
                    github_token: "${{ secrets.GITHUB_TOKEN }}"
                    branch: "${{ github.ref }}"
